<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media.proto

namespace Aparlay\Core\Microservices\ffmpeg;

use Aparlay\Core\Microservices\ffmpeg\GPBMetadata\Media;
use Exception;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>media.UploadRequest</code>.
 */
class UploadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bucket_name = 1;</code>.
     */
    private $bucket_name = '';

    /**
     * Generated from protobuf field <code>string bucket_id = 2;</code>.
     */
    private $bucket_id   = '';

    /**
     * Generated from protobuf field <code>string src = 3;</code>.
     */
    private $src         = '';

    /**
     * Generated from protobuf field <code>string des = 4;</code>.
     */
    private $des         = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     *     @type string $bucket_name
     *     @type string $bucket_id
     *     @type string $src
     *     @type string $des
     * }
     */
    public function __construct($data = null)
    {
        Media::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bucket_name = 1;</code>.
     *
     * @return string
     */
    public function getBucketName()
    {
        return $this->bucket_name;
    }

    /**
     * Generated from protobuf field <code>string bucket_name = 1;</code>.
     *
     * @param string $var
     *
     * @throws Exception
     *
     * @return $this
     */
    public function setBucketName($var)
    {
        GPBUtil::checkString($var, true);
        $this->bucket_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bucket_id = 2;</code>.
     *
     * @return string
     */
    public function getBucketId()
    {
        return $this->bucket_id;
    }

    /**
     * Generated from protobuf field <code>string bucket_id = 2;</code>.
     *
     * @param string $var
     *
     * @throws Exception
     *
     * @return $this
     */
    public function setBucketId($var)
    {
        GPBUtil::checkString($var, true);
        $this->bucket_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string src = 3;</code>.
     *
     * @return string
     */
    public function getSrc()
    {
        return $this->src;
    }

    /**
     * Generated from protobuf field <code>string src = 3;</code>.
     *
     * @param string $var
     *
     * @throws Exception
     *
     * @return $this
     */
    public function setSrc($var)
    {
        GPBUtil::checkString($var, true);
        $this->src = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string des = 4;</code>.
     *
     * @return string
     */
    public function getDes()
    {
        return $this->des;
    }

    /**
     * Generated from protobuf field <code>string des = 4;</code>.
     *
     * @param string $var
     *
     * @throws Exception
     *
     * @return $this
     */
    public function setDes($var)
    {
        GPBUtil::checkString($var, true);
        $this->des = $var;

        return $this;
    }
}
